#!/usr/bin/env bash
source /etc/sudo-comment.conf
tty="`tty | cut -d '/' -f 3-`"
if [ ! -p "$tmpdir/$tty" ]; then
	echo "No waitcomment process"
	exit
fi
mytmpdir="`cat "$tmpdir/$tty"`"
echo "Comment on an edit? [y/yp/N] " 
read -r comment
if [ "$comment" = "N" ]; then
	echo "N/A" > "$tmpdir"/"$tty" 
	echo "No comment added"
elif [ "$comment" = "yp" ]; then
	echo -e "=POSTDATED=" >> "$mytmpdir"/comment.tmp
	eval "$editor" "$mytmpdir"/comment.tmp
	echo "OK" > "$tmpdir"/"$tty"
	echo "Comment added"
else
	eval "$editor" "$mytmpdir"/comment.tmp
	echo "OK" > "$tmpdir"/"$tty"
	echo "Comment added"
fi
