#!/bin/bash
. /etc/sudo-comment.conf
if [ $# -eq 0 ]; then
	less "$commentlog"
elif [ $# -eq 1 ]; then
	commentlog_append="`cat "$commentlog" <(echo "@@")`"
	sed -n "/^@@/!{H;$!d};x;/$1/p" <<< "$commentlog_append" | less
else
	echo "Too many arguments."
fi
